import AppKit
import SwiftUI

/// The app's own icons — menu bar, Settings, the offline screen — from the
/// same Lucide kit the web workspace draws (vendor/lucide), so the window and
/// the chrome around it match.
///
/// NSImage draws SVG itself, so each icon is its markup (LucideData.swift,
/// generated by `npm run icons` from the names used here) made into a
/// template image: AppKit tints it like any symbol, in the menu bar and in
/// both appearances. Should a system ever decline the SVG, the SF Symbol
/// named beside it is drawn instead, so no control is left blank.
@MainActor
enum Lucide {
    private static var cache: [String: NSImage] = [:]

    static func image(_ name: String, size: CGFloat = 16, strokeWidth: Double = 2) -> NSImage {
        let key = "\(name)@\(size)/\(strokeWidth)"
        if let hit = cache[key] { return hit }
        let svg = """
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" color="black" \
        fill="none" stroke="black" stroke-width="\(strokeWidth)" stroke-linecap="round" stroke-linejoin="round">\
        \(LucideData.shapes[name] ?? "")</svg>
        """
        let image: NSImage
        if LucideData.shapes[name] != nil, let drawn = NSImage(data: Data(svg.utf8)), drawn.isValid {
            image = drawn
            image.size = NSSize(width: size, height: size)
            image.isTemplate = true
        } else {
            image = NSImage(systemSymbolName: fallback[name] ?? "questionmark", accessibilityDescription: nil)
                ?? NSImage(size: NSSize(width: size, height: size))
        }
        cache[key] = image
        return image
    }

    /// The nearest SF Symbol, for a system that cannot draw the SVG.
    private static let fallback: [String: String] = [
        "chevron-left": "chevron.left",
        "chevron-right": "chevron.right",
        "hard-drive": "externaldrive",
        "refresh-cw": "arrow.triangle.2.circlepath",
        "cloud-off": "icloud.slash",
        "cloud-download": "icloud.and.arrow.down",
        "triangle-alert": "exclamationmark.triangle",
        "wifi-off": "wifi.slash",
        "circle-user": "person.crop.circle",
        "database": "internaldrive",
    ]
}

extension Image {
    /// A Lucide icon as a template image (see `Lucide`).
    @MainActor
    init(lucide name: String, size: CGFloat = 16, strokeWidth: Double = 2) {
        self.init(nsImage: Lucide.image(name, size: size, strokeWidth: strokeWidth))
    }
}
