#!/usr/bin/env node
// Builds app/components/ui/icon-data.js — the shapes <Icon> draws — and
// apple/OnyxMac/LucideData.swift — the Mac app's — from the Lucide kit in
// vendor/lucide, keeping only the icons each uses.
//
//   npm run icons            regenerate
//   npm run icons -- --check exit 1 if either is out of date
//
// An icon is "used" when some file under app/ has <Icon name="…"> with a
// literal name, or lists it in an `icons:` comment — for names chosen at run
// time: /* icons: play pause */. So using a new icon is: write the JSX, run
// this. test/icons.test.js fails if one is missing.
//
// Only what is used ships because icon-data.js is in the client bundle; the
// whole kit is ~150 KB.
import { readFileSync, readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SPRITE = join(ROOT, 'vendor/lucide/sprite.svg');
const OUT = join(ROOT, 'app/components/ui/icon-data.js');
// The Mac app's own chrome (menu bar, Settings) draws the same kit.
const SWIFT_OUT = join(ROOT, 'apple/OnyxMac/LucideData.swift');

/** { name: [[tag, attrs], …] } for every symbol in the sprite. */
export function parseSprite(svg) {
  const icons = {};
  for (const [, name, body] of svg.matchAll(/<symbol id="icon-([a-z0-9-]+)"[^>]*>([\s\S]*?)<\/symbol>/g)) {
    icons[name] = [...body.matchAll(/<([a-z]+)\s+([^>]*?)\s*\/>/g)].map(([, tag, attrs]) => [
      tag,
      Object.fromEntries([...attrs.matchAll(/([a-zA-Z0-9:-]+)="([^"]*)"/g)].map(([, k, v]) => [k, v])),
    ]);
  }
  return icons;
}

function* sources(dir, ext) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) yield* sources(path, ext);
    else if (ext.test(entry) && !/(icon-data\.js|LucideData\.swift)$/.test(path)) yield path;
  }
}

// `icons: a b c` in a comment names icons chosen at run time.
function listed(text, names) {
  for (const [, list] of text.matchAll(/(?:\/\*|\/\/)\s*icons:\s*([a-z0-9 -]+?)\s*(?:\*\/|$)/gm)) {
    for (const n of list.split(/\s+/)) if (n) names.add(n);
  }
}

/** The icon names app/ uses, sorted. */
export function usedNames(root = ROOT) {
  const names = new Set();
  for (const file of sources(join(root, 'app'), /\.(js|jsx|mjs)$/)) {
    const text = readFileSync(file, 'utf8');
    for (const [, n] of text.matchAll(/<Icon\b[^>]*?\bname="([a-z0-9-]+)"/g)) names.add(n);
    listed(text, names);
  }
  return [...names].sort();
}

/** The icon names the Mac app uses — Image(lucide: "…"), Lucide.image("…") — sorted. */
export function usedSwiftNames(root = ROOT) {
  const names = new Set();
  for (const file of sources(join(root, 'apple/OnyxMac'), /\.swift$/)) {
    const text = readFileSync(file, 'utf8');
    for (const [, n] of text.matchAll(/(?:lucide:|Lucide\.image\()\s*"([a-z0-9-]+)"/g)) names.add(n);
    listed(text, names);
  }
  return [...names].sort();
}

const missingCheck = (icons, names) => {
  const missing = names.filter((n) => !icons[n]);
  if (missing.length) throw new Error(`Not in vendor/lucide: ${missing.join(', ')} (see vendor/lucide/icons.json for renamed icons)`);
};

/** LucideData.swift: each icon's shapes as SVG markup, for NSImage to draw. */
export function renderSwift(icons, names) {
  missingCheck(icons, names);
  const xml = (shapes) => shapes.map(([tag, a]) => `<${tag} ${Object.entries(a).map(([k, v]) => `${k}="${v}"`).join(' ')}/>`).join('');
  const lines = names.map((n) => `        "${n}": #"${xml(icons[n])}"#,`);
  return `// Generated by scripts/gen-icons.mjs from vendor/lucide (Lucide, ISC — see
// vendor/lucide/LICENSE). Do not edit: use Image(lucide:) and run \`npm run icons\`.
enum LucideData {
    static let shapes: [String: String] = [
${lines.join('\n')}
    ]
}
`;
}

export function render(icons, names) {
  missingCheck(icons, names);
  const attrs = (a) => `{ ${Object.entries(a).map(([k, v]) => `${/^[a-z]+$/i.test(k) ? k : `'${k}'`}: '${v}'`).join(', ')} }`;
  const lines = names.map((n) => `  '${n}': [${icons[n].map(([tag, a]) => `['${tag}', ${attrs(a)}]`).join(', ')}],`);
  return `// Generated by scripts/gen-icons.mjs from vendor/lucide (Lucide, ISC — see
// vendor/lucide/LICENSE). Do not edit: use <Icon name="…"> and run \`npm run icons\`.
const ICONS = {
${lines.join('\n')}
};

export default ICONS;
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const icons = parseSprite(readFileSync(SPRITE, 'utf8'));
  const check = process.argv.includes('--check');
  let stale = false;
  for (const [path, out, count] of [
    [OUT, render(icons, usedNames()), usedNames().length],
    [SWIFT_OUT, renderSwift(icons, usedSwiftNames()), usedSwiftNames().length],
  ]) {
    const rel = path.slice(ROOT.length + 1);
    let current = '';
    try { current = readFileSync(path, 'utf8'); } catch {}
    if (current === out) console.log(`${rel} is current.`);
    else if (check) { console.error(`${rel} is out of date: run \`npm run icons\`.`); stale = true; }
    else { writeFileSync(path, out); console.log(`Wrote ${rel} (${count} icons).`); }
  }
  if (stale) process.exit(1);
}
